---
version: "2.5"
services:
  tomcat:
    build:
       context: /home/azureuser/
    image: demotomcat:9.0
    ports:
      - 8081:8080
    volumes:
      - /alphavolume:/home/
    networks:
      - tomnetbridge
  test:
    build:
      context: /home/azureuser/
    image: demotomcat:9.0
    ports:
      - 8089:8080
    volumes:
      - /betavolume:/home/
    networks:
      - tomnetbridge
networks:
  tomnetbridge:
    external: true

